version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - internal

networks:
  internal : {}