version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - internal

volumes:
  pg-data:

networks:
  internal : {}